/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DramSimulator_DramSimulator */

#ifndef _Included_DramSimulator_DramSimulator
#define _Included_DramSimulator_DramSimulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DramSimulator_DramSimulator
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DramSimulator_DramSimulator_init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     DramSimulator_DramSimulator
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DramSimulator_DramSimulator_delete
  (JNIEnv *, jobject);

/*
 * Class:     DramSimulator_DramSimulator
 * Method:    tick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DramSimulator_DramSimulator_tick
  (JNIEnv *, jobject);

/*
 * Class:     DramSimulator_DramSimulator
 * Method:    will_accept
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_DramSimulator_DramSimulator_will_1accept
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     DramSimulator_DramSimulator
 * Method:    add_request
 * Signature: (LDramSimulator/DramRequest;)Z
 */
JNIEXPORT jboolean JNICALL Java_DramSimulator_DramSimulator_add_1request
  (JNIEnv *, jobject, jobject);

/*
 * Class:     DramSimulator_DramSimulator
 * Method:    check_read_response
 * Signature: ()LDramSimulator/DramResponse;
 */
JNIEXPORT jobject JNICALL Java_DramSimulator_DramSimulator_check_1read_1response
  (JNIEnv *, jobject);

/*
 * Class:     DramSimulator_DramSimulator
 * Method:    check_write_response
 * Signature: ()LDramSimulator/DramResponse;
 */
JNIEXPORT jobject JNICALL Java_DramSimulator_DramSimulator_check_1write_1response
  (JNIEnv *, jobject);

/*
 * Class:     DramSimulator_DramSimulator
 * Method:    get_clock_ticks
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_DramSimulator_DramSimulator_get_1clock_1ticks
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
